<?php

namespace AppBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{
}
