<?php

namespace AppBundle\Repository;

/**
 * DemandeParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
