<?php

namespace AppBundle\Repository;

/**
 * EntreeSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
