<?php

namespace AppBundle\Repository;

/**
 * FichierCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
