<?php

namespace AppBundle\Repository;

/**
 * InvitPariticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitPariticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
