<?php

namespace AppBundle\Repository;

/**
 * InvitParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
