<?php

namespace AppBundle\Repository;

/**
 * LangageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangageRepository extends \Doctrine\ORM\EntityRepository
{
}
