<?php

namespace AppBundle\Repository;

/**
 * OrganizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganiserRepository extends \Doctrine\ORM\EntityRepository
{
}
