<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProgramerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends EntityRepository
{
}
