<?php

namespace AppBundle\Repository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends \Doctrine\ORM\EntityRepository
{
}
