<?php

namespace AppBundle\Repository;

/**
 * ProgramerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramerRepository extends \Doctrine\ORM\EntityRepository
{
}
