<?php

namespace AppBundle\Repository;

/**
 * SolutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolutionRepository extends \Doctrine\ORM\EntityRepository
{
}
