<?php

namespace AppBundle\Repository;

/**
 * TypeParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
