<?php

namespace AppBundle\Repository;

/**
 * TypeEntreeSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEntreeSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
