AppBundle\Entity\Solution:
    type: entity
    inheritanceType: JOINED
    discriminatorColumn:
        name: _type
        type: string
        columnDefinition: null
        fieldName: _type
    repositoryClass: AppBundle\Repository\SolutionRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        updatedAt:
            type: datetime
            nullable: true
        cheminZip:
            type: string
            length: 255
            nullable: true
        tempsEnvoie:
            type: datetime
            nullable: false
        tempsExecution:
            type: float
            nullable: true
        correcte:
            type: boolean
            nullable: true
    oneToMany:
        fichiersCode:
            targetEntity: AppBundle\Entity\FichierCode
            cascade:
                - persist
            mappedBy: solution
            orphanRemoval: false
            orderBy: null
    manyToOne:
        participant:
            targetEntity: AppBundle\Entity\Participant
            cascade:
                - persist
            inversedBy: solutions
            joinColumns:
                participant_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
        langage:
            targetEntity: AppBundle\Entity\Langage
            cascade: {  }
            inversedBy: solutions
            joinColumns:
                langage_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
        probleme:
            targetEntity: AppBundle\Entity\Probleme
            cascade:
                - persist
            inversedBy: solutions
            joinColumns:
                probleme_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
